
language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-text
  - vendor/bin/ecs check src