
language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-text
  - vendor/bin/phpcs --standard=PSR2 src/